export const FEED_LIST = [
    { id: '1', name: 'Item!' },
    { id: '2', name: 'Item@' },
    { id: '3', name: 'Item#' },
    { id: '4', name: 'Item$' },
    { id: '5', name: 'Item%' },
    { id: '6', name: 'Item^' },
    { id: '7', name: 'Item&' },
    { id: '8', name: 'Item*' },
    { id: '9', name: 'Item(' },
    { id: '10', name: 'Item)' },
    { id: '11', name: 'Item!!' },
    { id: '12', name: 'Item@@' },
    { id: '13', name: 'Item##' },
    { id: '14', name: 'Item$$' },
    { id: '15', name: 'Item%%' },
    { id: '16', name: 'Item^^' },
    { id: '17', name: 'Item&&' },
    { id: '18', name: 'Item**' },
    { id: '19', name: 'Item((' },
    { id: '20', name: 'Item))' },
];