export const LONG_TEXT = "For my own sanity, I’ll then take a look and see which constants\
I’ve used multiple times across my project. There’s no reason to have them defined twice,\
and so I can actually cut down my code pretty significantly at scale by only having to define\
them once here. Once I’ve gotten all of my constants uniquely defined in index.js,\
I go ahead and break out each batch of constants further so that I can clearly understand\
what component is using what component. This obviously poses some minor issues when it comes to clarifying\
when a component is used twice, but it’s pretty easy to just add a little note here to clarify that.\
You’ll notice right away that in the case above, I actually have two constants that are the same value but are named differently.\
I did this because I felt that when I call “Constant.NEWACCOUNTURL” on my registration page it was clearer to read\
when building a new account as opposed to “Constant.EXISTINGACCOUNTURL” when contextually we are actually creating a new account.";

export const COMMENTS = [
    "#bornperfect  @cristiano ",
    "@cmeikkkkk @emilyng.__ C",
    "@cristiano we need a cappcononiere",
    "@cristiano ",
    "@dani.gouhie cheazzz qua e buono eh",
    "@jai_lm10  @vedantdaramwar  @thegoudfather  Ronaldo ke thighs dekh",
    "Are you looking for Web Scraping Bravo Cristiano !!",
    // "Brilha Bueno en esa liga como la alemana como que no hay competencia siempre lo mismo. felicidades",
    // "CH A M P I O N S",
    // "Champions ",
    // "Champions! ",
    // "Como siempre perfecto felicidades",
    // "Congcuratulation juve siiiuuu",
    // "Congrats ",
    // "Congrats ",
    // "Congratulations Brother  #Stron9er",
    // "Congratulations Cris",
    // "Congratulations champ ",
    // "Congratulations from UZBEKISTAN ",
    // "Congratulations on 9 championships. And I hope you become a champion. Also Congratulations to the team n cr7 #GOAT",
    // "Congratulations ",
    // "Congz bro! Keep winning trophies till the end of times. ",
    // "E vaiiiii",
    // "Eres el mejor CR7 Felicitaciones Forza Juve son los mejores",
    // "Exported Using ExportGram.Com Felicidades compadre",
    // "Felicissimo Juventus",
    // "Felicitaciones campeones",
    // "Follow me and msg me for my nde",
    // "Follow me please",
    // "Follow:- @simple_intresting_facts  to know some unique and intresting facts",
    // "For the season",
    // "Forza Cristiano forza Juve",
    // "Forza Juve Sempre",
    // "Forza Juve!!!! ",
    // "Forza Juventus.",
    // "Frenton iguainno?",
    // "G.O.A.T ",
    // "Gigante bro",
    // "Goat! ",
    // "Grande Paolo Hari dimana sangat emosional di saat jatuh bisa bangkit buktikan diri siapa juara sejati yg kuasa Italia ya itu juventus.forza Juve Indonesia",
    // "I fans you from Indonesia Mr @cristiano",
    // "Job well done ",
    // "Juve ",
    // "Let's go man u legend wish you the best",
    // "Nice.... group.... ",
    // "O maior de todos Promoo de tnis chama no direct ",
    // "Register on the 1 xbet website Renaldo i love you brother ",
    // "Selamat brow!!!",
    // "Senza rigori volevo vedere se vincevi",
    // "Sweet victory GOAT",
    // "Ta fibrado The real champion our christiano",
    // "UCL nya dong",
    // "Vamos cristiano tu tienes que quedar como goleador tambin animo",
    // "Vamos cristiano",
    // "Vamos ",
    // "Why do you only take penalties?",
    // "You too @natashayi",
    // "Zr ish bldi Dan shu golam urish kk edi kbraq",
    // "a boy from madeira with awesome achievements",
    // "atractive photo",
    // "campione ",
    // "campioni champion league dong just u cant ",
    // "the champ",
    // " @cristiano",
    // "#36 ",
    // " you are the best",
    // " come to @botafogo with @marcelotwelve",
    // "FIRE !",
    // " @deltaaire",
    // "W IL RE CRISTIANO RONALDO SIUUUU VAAAAMOSSSS FORZA JUVENTUS ",
];